{% set name = "flask-talisman" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c5f486f5f54420729f84b3c3850cd63f96e8b033a9629bee66c524ea363797ff
  - url: https://raw.githubusercontent.com/wntrblm/flask-talisman/v{{ version }}/LICENSE
    sha256: c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - flask

test:
  requires:
    - flask
    - python {{ python_min }}
  imports:
    - flask_talisman

about:
  home: https://github.com/GoogleCloudPlatform/flask-talisman
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

  summary: HTTP security headers for Flask
  description: |
    Talisman is a small Flask extension that handles setting HTTP headers that can help 
    protect against a few common web application security issues.

  dev_url: https://github.com/GoogleCloudPlatform/flask-talisman

extra:
  recipe-maintainers:
    - sodre
    - xmnlab
